const Too = () => {
  return (
    <section>
      <table>
        <thead>
          <tr>
            <th></th>
            <th>
              <strong>ᠲᠡᠭ</strong>
            </th>
            <th>
              <strong>ᠨᠢᠭᠡ</strong>
            </th>
            <th>
              <strong>ᠬᠤᠶᠤᠷ</strong>
            </th>
            <th>
              <strong>ᠭᠤᠷᠪᠠ</strong>
            </th>
            <th>
              <strong>ᠳᠥᠷᠪᠡ</strong>
            </th>
            <th>
              <strong>ᠲᠠᠪᠤ</strong>
            </th>
            <th>
              <strong>ᠵᠢᠷᠭᠤᠭ᠎ᠠ</strong>
            </th>
            <th>
              <strong>ᠳᠤᠯᠤᠭ᠎ᠠ</strong>
            </th>
            <th>
              <strong>ᠨᠠᠢ᠋ᠮᠠ</strong>
            </th>
            <th>
              <strong>ᠶᠢᠰᠥ</strong>
            </th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>Монгол</td>
            <td>
              <strong>&#x1810;</strong>
            </td>
            <td>
              <strong>&#x1811;</strong>
            </td>
            <td>
              <strong>&#x1812;</strong>
            </td>
            <td>
              <strong>&#x1813;</strong>
            </td>
            <td>
              <strong>&#x1814;</strong>
            </td>
            <td>
              <strong>&#x1815;</strong>
            </td>
            <td>
              <strong>&#x1816;</strong>
            </td>
            <td>
              <strong>&#x1817;</strong>
            </td>
            <td>
              <strong>&#x1818;</strong>
            </td>
            <td>
              <strong>&#x1819;</strong>
            </td>
          </tr>
          <tr>
            <td>Араб</td>
            <td>0</td>
            <td>1</td>
            <td>2</td>
            <td>3</td>
            <td>4</td>
            <td>5</td>
            <td>6</td>
            <td>7</td>
            <td>8</td>
            <td>9</td>
          </tr>
        </tbody>
      </table>
    </section>
  );
};
export default Too;
