export const ADD_CATEGORY_ERROR = "ADD_CATEGORY_ERROR";
export const ADD_CATEGORY_LOADING = "ADD_CATEGORY_LOADING";
export const ADD_CATEGORY_SUCCESS = "ADD_CATEGORY_SUCCESS";

export const DELETE_CATEGORY_ERROR = "DELETE_CATEGORY_ERROR";
export const DELETE_CATEGORY_LOADING = "DELETE_CATEGORY_LOADING";
export const DELETE_CATEGORY_SUCCESS = "DELETE_CATEGORY_SUCCESS";

export const EDIT_CATEGORY_ERROR = "EDIT_CATEGORY_ERROR";
export const EDIT_CATEGORY_ERROR = "EDIT_CATEGORY_ERROR";
export const EDIT_CATEGORY_ERROR = "EDIT_CATEGORY_ERROR";

export const FETCH_CATEGORY_ERROR = "FETCH_CATEGORY_ERROR";
export const FETCH_CATEGORY_ERROR = "FETCH_CATEGORY_ERROR";
export const EFETCH_CATEGORY_ERROR = "FETCH_CATEGORY_ERROR";
