export const CREATE_CATEGORY = "CREATE_CATEGORY";
export const READ_CATEGORIES = "READ_CATEGORIES";
export const READ_CATEGORY = "READ_CATEGORY";
export const UPDATE_CATEGORY = "UPDATE_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
